first/urls.py
from . import views
from django.urls import path, include
urlpatterns = [
    path('', views.index, name='index'),
    path('studendts', views.students, name='studendts'),
    path('scores', views.score, name='scores')
]

second/urls.py
from . import views
from django.urls import path, include

app_name="second"

urlpatterns = [
    path('', views.index, name='index'),
    path('favorite', views.favorite, name='favorite'),
    path('todo', views.todo, name='todo'),
    path('favorite/<seq>', views.favorite_detail, name='favorite_detail')
]

todo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('first/', include('first.urls')),
    path('second/', include('second.urls'))
]

first/models.py
from django.db import models

# Create your models here.

class Studendts(models.Model):
    name = models.CharField(max_length=10)
    adress = models.CharField(max_length=50)
    email = models.CharField(max_length=30, default='')

class scores(models.Model):
    name = models.CharField(max_length=10)
    math = models.CharField(max_length=50)
    english = models.CharField(max_length=50)
    science = models.CharField(max_length=50)

second/models.py
from django.db import models

# Create your models here.
class FavoriteGroup(models.Model):
    seq = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50)
    reg_date = models.DateField(auto_now_add=True)
    
    def __str__(self):
        return self.name

class Favorite(models.Model):
    seq = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50)
    url = models.CharField(max_length=100)
    memo = models.TextField()
    reg_date = models.DateField(auto_now_add=True)
    group = models.ForeignKey(FavoriteGroup, on_delete=models.CASCADE)

class TodoGroup(models.Model):
    seq = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50)
    reg_date = models.DateField(auto_now_add=True)
    
    def __str__(self):
        return self.name

class Todo(models.Model):
    seq = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50)
    url = models.CharField(max_length=100)
    memo = models.TextField()
    reg_date = models.DateField(auto_now_add=True)
    group = models.ForeignKey(TodoGroup, on_delete=models.CASCADE)

first/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Studendts
from .models import scores

# Create your views here.
def index(request):
    return render(request, 'first/index.html')

def students(request):

    students = Studendts.objects.all()
    print(students) 
    """
        SELECT *
            FROM studendts
    """
    return render(request, 'first/students.html', {
        'text':'안녕하세요',
        'students' : students
    })

def score(request):
    
    scores2 = scores.objects.all()
    print(scores2) 
    """
        SELECT *
            FROM scores
    """
    return render(request, 'first/scores.html', {
        'text':'안녕하세요',
        'scores' : scores2
    })

second/views.py
from django.shortcuts import render
from .models import Favorite, Todo
# Create your views here.
def index(request):
    return render(request, "second/index.html")

def favorite(request):
    data = Favorite.objects.all()
    return render(request, "second/favorite.html",
        {'datas':data}
    )
def todo(request):
    data = Todo.objects
    if 'group' in request.GET:
        data = data.filter(group__name=request.GET['group'])
    if 'end_date' in request.GET:
        data = data.filter(end_date__gte=request.GET['end_date'])
    return render(request, "second/todo.html",
        {'datas':data.all()}
    )

def favorite_detail(request, seq):
    detail = Favorite.objects.get(pk=seq)
    return render(request, "second/favorite_detail.html",{
        'detail' : detail
    })
    
    
    

first/templates/first/index.html
<html>
<head>
    <title>환영합니다</title>
</head>
<body>
    <h3>환영합니다</h3>
</body>
</html>

first/templates/first/layout.html
<!DOCTYPE html>
<html
<head>
    {% block title %}
    {% endblock %}
</head>
<body>
    <a href="/first/students"/>학생정보</a>
    <a href="/first/scores"/>점수정보</a>
    {% block content %}
    {% endblock %}
</body>
</html>

first/templates/first/scores.html
{% extends 'first/layout.html' %}
 {% block title %}
 <title>점수</title>
 {% endblock %}
 {% block content %}
 <table>
 <thead>
    <tr>
        <td>이름</td><td>수학</td><td>과학</td><td>영어</td>
    </tr>
</thead>
{% for score in scores %}
    <tr>
        <td>{{ score.name }}</td>
        <td>{{ score.math }}</td>
        <td>{{ score.science }}</td>
        <td>{{ score.english }}</td>
    </tr>
{% endfor %}
</table>
{% endblock %}

first/templates/first/students.html
{% extends 'first/layout.html' %}
{% block title %}
<title>학생들</title>
{% endblock %}
{% block content %}
    <h3>{{ text|truncatechars:10 }}</h3>
    <h3>{{ date|date:'Y-m-d' }}</h3>
    {% for student in students %}
    <!-- 요 안에있는 내용들이 반복됩니다 -->
    <div>
        {{ student.name }}
        {{ student.address }}
        {{ student.email }}
    </div>
    {% endfor %}
{% endblock %}

second/templates/second/favorite.html
{% extends 'second/layout.html' %}
{% block title %}
즐겨찾기
{% endblock %}
{% block content %}
<h3>즐겨찾기</h3>
<div>
{% for data in datas %}
    <div class="item">
        <div class="name">
            <a href="{% url 'second:favorite_detail' data.seq %}">
            {{ data.name }}
            </a>
        </div>
        <div class="group">
            {{ data.group }}
        </div>
        <div class="regdate">
            {{ data.reg_date|date:"Y-m-d" }}
        </div>
    </div>
{% endfor %}
</div>
{% endblock %}

second/templates/second/favorite_detail.html
{% extends 'second/layout.html' %}
{% block title %}
즐겨찾기 상세
{% endblock %}
{% block content %}
<h3>즐겨찾기 상세</h3>
<div id="detail">
    <ul>
        <li><span>순번</span>{{detail.seq}}</li>
        <li><span>이름</span>{{detail.name}}</li>
        <li><span>주소</span>{{detail.url}}</li>
        <li><span>메모</span>{{detail.memo}}</li>
        <li><span>날짜</span>{{detail.reg_date}}</li>
        <li><span>그룹</span>{{detail.group}}</li>
        
       
    </ul>
</div>
{% endblock %}

second/templates/second/index.html
{% load static %}
<html>
<head>
    <title>환영합니다</title>
</head>
<body>
    <h3>환영합니다</h3>
    <img src="{%static 'second/sky.jpg' %} "
</body>
</html>

second/templates/second/layout.html
<!DOCTYPE html>
<html>
<head>
    <title>
        {% block title %}
        {% endblock %}
    </title>
    <style>
        html, body, ul {
            margin: 0;
            padding: 0;
        }
        html, body {
            height: 100%;
            background-color: #f5f5fb;
        }
        ul {
            list-style:none;
        }
        #menu, #content {
            float: left;
        }
        #menu {
            background-color: #4c4cab;
            width: 200px;
            height: 100%;
        }
        #menu #logo {
            margin-top: 20px;
            color: white;
            font-weight: 700;
            font-size: 20px;
            text-align: center;
        }
        #menu ul {
            margin-top: 40px;
        }
        #menu ul a {
            color: #bbbbe5;
            text-decoration: none;
        } 
        #menu ul li {
            color: #bbbbe5;
            margin-bottom: 10px;
            font-size: 15px;
            padding-left: 30px;
        }
        #content {
            padding-left: 30px;
        }
        h3 {
            width: 800px;
            border-bottom: 1px solid #c8c8cd;
            font-size: 30px;
            margin-bottom: 50px;
        }
        #content .item {
            padding: 15px;
            overflow: auto;
            border: 1px solid #c8c8cd;
            border-radius: 6px;
            margin-bottom: 10px;
            background-color: white;
        }
        #content .name {
            float: left;
        }
        #content .regdate {
            margin-right: 10px;
        }
        #content .regdate,  #content .group{
            float: right;
        }
        #content .items {
            width: 33%;
            box-sizing: border-box;
            float: left;
            padding-left: 10px;
        }
        #content .items-title {
            text-align: center;
            margin-bottom: 10px;
            font-size: 20px;
            font-weight: 700;
        }

        #detail{
            width: 800px;
            background-color: white;
            padding: 30px;
            box-sizing: border-box;
            border: 1px solid #c8c8cd;
            border-radius: 6px;
        }

        #detail ul li {
            margin:
        }

        #detail ul span {
            display: inline-block;
            width: 100px;
        }
    </style>
</head>
<body>
    <div id="menu">
        <div id="logo">Todo&Favorite</div>
        <ul>
            <li><a href="{% url 'second:index' %}">Home</a></li>
            <li><a href="{% url 'second:favorite' %}">Favorite</a></li>
            <li><a href="{% url 'second:todo' %}">Todo</a></li> 
        </ul>
    </div>
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

second/templates/second/todo.html
{% extends 'second/layout.html' %}
{% block title %}
할일
{% endblock %}
{% block content %}
<h3>할일</h3>
<div class="items">
<div class="items-title">할일</div>
{% for data in pendings %}
    <div class="item">
        <div class="name">
            {{ data.name }}
        </div>
        <div class="group">
            {{ data.group }}
        </div>
        <div class="regdate">
            {{ data.reg_date|date:"Y-m-d" }}
        </div>
    </div>
{% endfor %}
</div>
<div class="items">
<div class="items-title">진행중</div>
{% for data in inprogresss %}
    <div class="item">
        <div class="name">
            {{ data.name }}
        </div>
        <div class="group">
            {{ data.group }}
        </div>
        <div class="regdate">
            {{ data.reg_date|date:"Y-m-d" }}
        </div>
    </div>
{% endfor %}
</div>
<div class="items">
<div class="items-title">완료</div>
{% for data in ends %}
    <div class="item">
        <div class="name">
            {{ data.name }}
        </div>
        <div class="group">
            {{ data.group }}
        </div>
        <div class="regdate">
            {{ data.reg_date|date:"Y-m-d" }}
        </div>
    </div>
{% endfor %}
</div>
{% endblock %}